[phases.setup]
nixPkgs = ["python311", "gcc", "gnumake", "cmake", "libglvnd", "glib"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn face_auth_api:app --host 0.0.0.0 --port $PORT"
